### ISSUE TITLE
SuperFly for Deltas

### ISSUE THREAD

**Issue by Foxies-CSTL** [mustcode/superfly#1]
Hello,
First of all, congratulations for your design!
I have come across your mini-extruder by chance and I am very interested because I have the ideas but not your skills to design this type of object ;-) . Currently I am trying to make tests with a mini-sherpa on a Delta printer assembly but I have an unbalance because the motor is too high. With yours, I will gain height but the best would be to put the motor at the bottom (I have space). I made some rough modifications and printed a draft to see if it goes better (motor at the bottom). If it works mechanically, could you modify the stepper motor attachments as described above?

![image](https://user-images.githubusercontent.com/24864147/117534344-471d1700-aff1-11eb-8155-8c0fcfd4b644.png)
![image](https://user-images.githubusercontent.com/24864147/117534369-6156f500-aff1-11eb-820b-82236c3a293e.png)
![image](https://user-images.githubusercontent.com/24864147/117535281-5900b900-aff5-11eb-99e6-0c19227b2ff6.png)

sig. Foxies

**Comment by mustcode** [comment]
Nicely done! I'm interested too see how this works out for you, so please do let me know 😄

**Comment by Foxies-CSTL** [comment]
Hi, 
I finished my tests with your modified extruder. Here is a feedback:
-Assembly is fairly easy, just need a mounting bracket between the extruder and the HotEnd assembly.
![image](https://user-images.githubusercontent.com/24864147/118358625-09376a00-b580-11eb-868d-d787d9311a94.png)
![image](https://user-images.githubusercontent.com/24864147/118358670-35eb8180-b580-11eb-958c-7be26d2e49a0.png)

-My 3D modification is not great because I am not good at modeling ;-) but it works for your tests.
-I had to print the SuperFly body from 101.1% to avoid friction in the assembly.
-The double gear part doesn't work well because it is limited in filament clamping. 
-The hole to put the PTFE tube is not long enough (height/depth) to easily remove the tube. The clearance is too small.
-The holes for mounting the stepper motor are too high/double which makes the position of the motor gear slightly off. I re-printed a template without holes to make them after positioning/adjusting the stepper motor.

![image](https://user-images.githubusercontent.com/24864147/118358723-721ee200-b580-11eb-995e-098fa5c6ac69.png)
![image](https://user-images.githubusercontent.com/24864147/118358749-8f53b080-b580-11eb-906d-1e23b4852185.png)


I couldn't print it because I had this problem of the filament drive slipping but with these few modifications, this model is very promising for the Deltas. 

Thank you for being able to integrate these modifications that I will test with great interest ;-)
See you later, have a good day .

A few details:
NEMA14 motor
Hotend Volcano 50W
Delta QQS-Pro

**Comment by mustcode** [comment]
Thank you for the great feedback! I really appreciate them as all the feedback will be what drives the changes in the next iteration.
Also, if you're having issue with filament slipping, try the high-tension version of the tensioner. It was added in after another person reported that the regular tensioner can only hold up to about 80mms, so I made the high version tension which can have a much stronger clamping force.
Also, I noticed that you're not using a Bowden collet, so, I'd recommend using a collet as the hole was designed to fit a collet. It'll help with inserting and removing the PTFE tube.
Cheers!

**Comment by Foxies-CSTL** [comment]
Hi, 
> Thank you for the great feedback! I really appreciate them as all the feedback will be what drives the changes in the next iteration.
> Also, if you're having issue with filament slipping, try the high-tension version of the tensioner. It was added in after another person reported that the regular tensioner can only hold up to about 80mms, so I made the high version tension which can have a much stronger clamping force.
> Also, I noticed that you're not using a Bowden collet, so, I'd recommend using a collet as the hole was designed to fit a collet. It'll help with inserting and removing the PTFE tube.
> Cheers!

![image](https://user-images.githubusercontent.com/24864147/119132961-a2142c80-ba3b-11eb-9e9c-3e565a7e519d.png)

I used bodwen pliers but the gap is not high enough to remove the PTFE without forcing. I also used my tensioner modification. It's better but with my poor inverted motor modification, I have difficulties to get a good grip on the filament. I printed a screen cover in ABS at 80mm/s and I have to watch it because some times it slips (I will put a video). Can you make me a model like mine so I can continue my high speed tests.
Regards,

**Comment by mustcode** [comment]
Well, it's not hard to invert, so here it is. But I'm not sure if it'll be any different from yours, so hopefully, this can help you out.
[https://drive.google.com/file/d/1rzZCqRGrUaCEFf2a5QW4L-ouQXXRABdQ/view?usp=sharing](https://drive.google.com/file/d/1rzZCqRGrUaCEFf2a5QW4L-ouQXXRABdQ/view?usp=sharing)

**Comment by Foxies-CSTL** [comment]
> 
> 
> Well, it's not hard to invert, so here it is. But I'm not sure if it'll be any different from yours, so hopefully, this can help you out.
> https://drive.google.com/file/d/1rzZCqRGrUaCEFf2a5QW4L-ouQXXRABdQ/view?usp=sharing

Oh thanks!! Do I have to use FreeCad to transform it into an STL?

**Comment by Fonsecal** [comment]
> > Well, it's not hard to invert, so here it is. But I'm not sure if it'll be any different from yours, so hopefully, this can help you out.
> > https://drive.google.com/file/d/1rzZCqRGrUaCEFf2a5QW4L-ouQXXRABdQ/view?usp=sharing
> 
> Oh thanks!! Do I have to use FreeCad to transform it into an STL?

Yes , FreeCad  / export / STL

Foxies-CSTL If you can share your suport for the FLSun I will give a try .

Thanks

**Comment by Foxies-CSTL** [comment]
> Yes , FreeCad / export / STL
> 
> Foxies-CSTL If you can share your suport for the FLSun I will give a try .

Thanks, I had found it ;-)
Here is the support for the SuperFlyDelta.
[QQS_Mount-SuperFly.zip](https://github.com/mustcode/superfly/files/6529223/QQS_Mount-SuperFly.zip)

https://user-images.githubusercontent.com/24864147/119475389-66d07100-bd4d-11eb-8e7b-f0780e0009ad.mp4

**Comment by mustcode** [comment]
Looks great! I'm glad it worked out :D

**Comment by Fonsecal** [comment]
> > Yes , FreeCad / export / STL
> > 
> > Foxies-CSTL If you can share your suport for the FLSun I will give a try .
> 
> Thanks, I had found it ;-)
> Here is the support for the SuperFlyDelta.
> [QQS_Mount-SuperFly.zip](https://github.com/mustcode/superfly/files/6529223/QQS_Mount-SuperFly.zip)
> 
> https://user-images.githubusercontent.com/24864147/119475389-66d07100-bd4d-11eb-8e7b-f0780e0009ad.mp4
> 
> 
> 
> 
> 

Thanks Foxies-CSTL, I have  printed  the support file but is not the complete mount to try on a FLSun QQ s pro . Anyway if possible to share will be great. ![IMG_20210527_220055.jpg](https://user-images.githubusercontent.com/84633645/119896541-11f04e80-bf37-11eb-83ab-72971652ebd9.jpg)
